USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE API INTEGRATION SF_WS_GIT_INTEGRATION
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/paulananth')
  API_USER_AUTHENTICATION = (TYPE = SNOWFLAKE_GITHUB_APP)
  ENABLED = TRUE;

-- grant usage on the API integration to all users
GRANT USAGE ON INTEGRATION SF_WS_GIT_INTEGRATION TO ROLE PUBLIC;