--ETF_DB.LOCAL_COPY.ANALYST2
USE ROLE ACCOUNTADMIN;
ALTER ACCOUNT SET ENABLE_CORTEX_ANALYST = TRUE;

GRANT USAGE ON DATABASE ETF_DB TO ROLE cortex_user_role;
GRANT USAGE ON SCHEMA ETF_DB.LOCAL_COPY TO ROLE cortex_user_role;

-- List all semantic models
SHOW SEMANTIC VIEWS IN SCHEMA ETF_DB.LOCAL_COPY;

-- Describe the semantic model
DESC SEMANTIC VIEW ETF_DB.LOCAL_COPY.ANALYST2;

-- Check your Snowflake version and region
SELECT CURRENT_VERSION(), CURRENT_REGION();

